### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by cmp0xff** [kausalflow/hamilflow#5]
`Hamiltonian_flow` may be too long of a name. TensorFlow has two syllables and six letters in the "tensor" part, whereas "hamiltonian" has four and eleven, respectively.

We probably need to make it shorter to make it easier to advertise...

Candidates from my side:
- HamiltonFlow
- HamilFlow
- HamiFlow
cc @ErbB4 @emptymalei

**Comment by emptymalei** [comment]
Instead of xxflow, we can use acronyms.

https://acronymify.com/search?q=physical+and+dynamical+systems+dataset

Some candidates:

1. [PLAID](https://acronymify.com/PLAID/?q=physical+and+dynamical+systems+dataset)
2. [PHYSICIST](https://acronymify.com/PHYSICIST/?q=physical+and+dynamical+systems+dataset)
4. [IDEA](https://acronymify.com/IDEA/?q=physical+and+dynamical+systems+dataset)
5. [INDICATE](https://acronymify.com/INDICATE/?q=physical+and+dynamical+systems+dataset)
6. [PALLET](https://acronymify.com/PALLET/?q=physical+and+dynamical+systems+dataset)

**Comment by cmp0xff** [comment]
I still believe Hamiltonian is a good idea, and would like to keep a part of the word Hamiltonian in the name.

**Comment by emptymalei** [comment]
No strong opinion here. HamiltonFlow sounds good. The important thing is to publish a first version ASAP to take the name on pip.

**Comment by emptymalei** [comment]
If you are fine with the name HamiltonFlow, we can refactor the code to this name.

**Comment by emptymalei** [comment]
we use HamilFlow
